const SELECTORS = {
  ROOT: '.root',
  HEADER: 'header',
  MAIN: 'main',
  HEADER_LINK_ACTIVE: 'header__link_state_active',
  PAGE_NUM_FIELD: '.section__page-num',
  PAGES_QTY: '.section__page-qty',
  ITEMS_QTY: '.section__items-qty',
  PAGINATION_PREV_BTN: '.section__prev-btn',
  PAGINATION_NEXT_BTN: '.section__next-btn',
  SECTION_CONTENT: '.section__content',
  BTN_INACTIVE: 'btn_inactive',
  HIDDEN: 'hidden',
  CONTROL: 'control',
  CONTROL_RACE_BTN: '.control__race-btn',
  CONTROL_RESET_BTN: '.control__reset-btn',
  CONTROL_GENERATE_BTN: '.control__generate-btn',
  CONTROL_CREATE_BTN: '.control__create-btn',
  CONTROL_CANCEL_BTN: '.control__cancel-btn',
  CONTROL_COLOR_INPUT: '.control__input_type_car-color',
  CONTROL_NAME_INPUT: '.control__input_type_car-name',
  CONTROL_OPTIONAL_BTNS: '.control__btns',
  CAR_START_BTN: '.car__start-btn',
  CAR_STOP_BTN: '.car__stop-btn',
  CAR_EDIT_BTN: '.car__edit-btn',
  CAR_REMOVE_BTN: '.car__remove-btn',
  CAR_PICTURE: '.car__car',
  CAR: 'car',
  FLAG: '.car__finish-flag',
  CAR_TITLE: '.car__title',
  WINNER: 'winner',
};

export default SELECTORS;
